### ISSUE TITLE
lenient decode functions

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/chronos#11]
It would be kind of nice to have a decode function that tried to parse a datetime several different ways. One that could accept any of the following:

    2017-01-05T23:13:05
    2017-01-05 23:13:05
    2017/01/05 23:13:05
    etc.

**Comment by chessai** [comment]
Would it just try all possible permutations of DatetimeFormat, constrained to the set of characters {':', '/', and ' '}?

Or, should it take a list DatetimeFormat and instead attempt each?

**Comment by andrewthad** [comment]
I think that we could just have it accept anything that did not use a numeric separator.  So, even something like

    2018x01y01/23;50&29

 Would be allowed.

**Comment by chessai** [comment]
Oh, you mean REALLY lenient. Ok. Makes sense

**Comment by ssbothwell** [comment]
I would like to take a stab at this issue. The parse should succeed with any non-numeric ascii character?

**Comment by chessai** [comment]
i think all implementations should succeed with any non-numeric ascii character, yes.

i think there should be one for each of those, and another, final one that combines them all, with documentation pointing out that it is potentially the slowest since it can do so much backtracking.

**Comment by ssbothwell** [comment]
No problem. Should it restrict to ascii or allow any unicode? Do you allow non-ascii elsewhere?

**Comment by chessai** [comment]
the default Parser is a Text parser, and parsers marked with UTF-8 are bytestring encoded UTF-8 parsers. i think you should be able to just use the `char` functions provided by attoparsec and be okay.

**Comment by ssbothwell** [comment]
:+1:

**Comment by chessai** [comment]
Fixed in #41
