### ISSUE TITLE
lenses

### ISSUE THREAD

**Issue by andrewthad** [andrewthad/chronos#14]
It's possible to add lenses for some of these things. If someone wants to do it, I'll take a PR. For documentation reasons, do the unexported type synonym thing that Gabriel does in [pipes-parse](http://hackage.haskell.org/package/pipes-parse-3.0.8/docs/Pipes-Parse.html) so that the haddocks end up nice.

**Comment by chessai** [comment]
I know I'm the one who suggested this to you, but I think lenses in this library might be a bit silly.

**Comment by andrewthad** [comment]
I’ll go ahead and close this since there’s no one who currently would use this feature.  But, I’m always happy to re-open it if there is there is a lens-lover out there would eoukd benefit from this.
