### ISSUE TITLE
fails to compile on mac

### ISSUE THREAD

**Issue by 2mol** [andrewthad/chronos#20]
Hi! I'm using version 1.0.3, compilation fails at the C step:

```
[4 of 4] Compiling Chronos.Locale.English ( src/Chronos/Locale/English.hs, dist/build/Chronos/Locale/English.o )
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]

src/cbits/hs-time.c:4:5: error:
     error: conflicting types for 'clock_gettime'
  |
4 | int clock_gettime(int clk_id, struct timespec* t) {
  |     ^
int clock_gettime(int clk_id, struct timespec* t) {
    ^

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/time.h:177:5: error:
     note: previous declaration is here
    |
177 | int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    |     ^
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
1 error generated.
`clang' failed in phase `C Compiler'. (Exit code: 1)
```

Let me know if I can give you more information!

**Comment by andrewthad** [comment]
I’m afraid I don’t have access to any Apple products. I would take a PR that fixes this, but I have no way to confirm that it does the right thing.

**Comment by chessai** [comment]
It looks like the definition is conflicting with something in `time.h`. Currently hs-time.c implements `clock-gettime` only if the system is a Mac, and there's a note saying it believes that this function is not implemented on Mac, which could be untrue as of now. Which OS version are you using @2mol ?

**Comment by chessai** [comment]
According to this PR https://github.com/zeromq/libzmq/issues/2175, macOS SDK 10.12 is what implements clock_gettime as your system reports it should

**Comment by chessai** [comment]
@2mol, can you try this out? https://github.com/andrewthad/chronos/tree/macos1012

**Comment by 2mol** [comment]
Hi @chessai, thanks for chiming in so fast! I will pull and build yous code asap.

**Comment by chessai** [comment]
Unfortunately I dont have a mac either but this was my best initial effort
based on what I found online.

**Comment by chessai** [comment]
Also the internal module in Chronos might need tweaking but I could be
wrong.

**Comment by 2mol** [comment]
So it compiles and passes `cabal new-test` and `cabal new-bench`!

`cabal new-build` complains about 'no symbols' in hs-time.o, but that seems to be just a warning.

I'm still running `stack build` (and nix being nix fails on `tf-random-0.5`), but I think it's safe to say that you fixed it.

Thanks for the amazing and fast response!

**Comment by chessai** [comment]
Cool, no. @andrewthad can you PR and merge that branch? I'm out right now

**Comment by andrewthad** [comment]
Merged.

**Comment by 2mol** [comment]
Any idea when you'd bump the version and put it on hackage?

**Comment by andrewthad** [comment]
I’ll do a new release today.

**Comment by andrewthad** [comment]
Released
