### ISSUE TITLE
drop `clock` dep in favour of GHC.Clock

### ISSUE THREAD

**Issue by chessai** [andrewthad/chronos#29]
we cannot do this until `chronos` only supports `base >= 4.11`

**Comment by andrewthad** [comment]
When GHC 8.10 comes out, we'll make this switch.

**Comment by chessai** [comment]
okay. I thought we may be able to just FFI into `getMonotonicTimeNSec` which we define ourselves, but it's defined in the rts and I don't feel like tracing through the definition right now.

**Comment by chessai** [comment]
i wish 8.10 was out. i don't think i ever told you this, but there was a guy who noticed that chronos' stopwatch functions were slower than similar machinery in another library (maybe `time`), and i recommended he just do `do { time0 <- now; a <- ...; time1 <- now; pure (a, time1 - time0); }` and it was a lot faster.

actually, we can do this right now with CPP.
