### ISSUE TITLE
Consider using `intervals` instead of baked in interval type

### ISSUE THREAD

**Issue by masaeedu** [andrewthad/chronos#34]
There's a nice package [here](https://hackage.haskell.org/package/intervals) that just adds intervals to an arbitrary ordered type (and provides a wealth of operations with respect to them). E.g. here's some fiddling with the `time` package and `intervals` to implement something someone was asking about in slack:

```haskell
module Main where

import Data.Time
import Numeric.Interval
import Numeric.Interval as I
import Data.Functor.Compose

type Event a t = (Maybe a, Interval t)

findEvents :: Ord t => Interval t -> [Event a t] -> [Event a t]
findEvents i =
  filter (not . I.null . snd)
  . getCompose
  . fmap (intersection i)
  . Compose

calendar :: [Event String Day]
calendar =
  [ (Just "event1", read "2019-01-01" ... read "2019-01-05")
  , (Just "event2", read "2019-01-03" ... read "2019-02-12")
  , (Just "event3", read "2019-03-01" ... read "2019-03-05")
  ]

test = read "2019-01-02" ... read "2019-01-05"

main :: IO ()
main = print $ findEvents test calendar
-- [ (Just "event1",2019-01-02 ... 2019-01-05)
-- , (Just "event2",2019-01-03 ... 2019-01-05)
-- ]
```

Does it make sense to just use this package instead of having a built in `TimeInterval`?

**Comment by chessai** [comment]
I briefly considered this, but ultimately it will be less peformant since
it wouldn't allow the `Time` values to unbox. I think if users want any
more functionality then writing the conversion function should be
sufficient.

**Comment by masaeedu** [comment]
@chessai Is that the case even with `Numeric.Interval.NonEmpty.Interval`? I don't know much about boxing/unboxing, but is there really any overhead if you're sticking `Time` in:

```
data Interval a = I !a !a
```

?

**Comment by chessai** [comment]
No, because haskell does not support polymorphic unpacking. So the `a`s there will not unpack.

GHC will tell you this with a simple program:

```haskell
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -Wall #-}
module Foo where

data Foo1 a = Foo1 {-# UNPACK #-} a

data Foo2 a = Foo2 {-# UNPACK #-} !a
```

GHC should complain about both unpack pragmas being redundant because they don't accomplish anything.

**Comment by chessai** [comment]
Given that the primary goal of chronos is high performance, having the Int# unpack into the data constructor seems very important.

**Comment by masaeedu** [comment]
Ok, makes sense.

**Comment by chessai** [comment]
Thank you for the issue though! The interest in our library is highly
appreciated.
