### ISSUE TITLE
Add Appveyor CI for Windows builds

### ISSUE THREAD

**Issue by vrom911** [andrewthad/chronos#42]
Appveyor is free and working smoothly for Windows checks. We use it for @kowainik projects.
It doesn't take much effort to support, however, it could help to prevent situations with broken releases of `chronos`.

If you agree I can help with the config. As the reference, here how it would look like:

https://github.com/kowainik/summoner/blob/master/appveyor.yml

**Comment by chessai** [comment]
That sounds awesome. We would love a PR/guidance on appveyor CI. thanks!
