### ISSUE TITLE
No way to obtain DayOfWeek

### ISSUE THREAD

**Issue by jm4games** [andrewthad/chronos#48]
I've look through the API and it seems like there is no way to obtain the day of week. Did I miss something?

**Comment by chessai** [comment]
You're right, this is an oversight! We probably want a function

datetimeToDayOfWeek :: Datetime -> DayOfWeek
datetiimeToDayOfWeek = ...

and then

getDayOfWeek :: IO DayOfWeek
getDayOfWeek = fmap (datetimeToDayOfWeek . timeToDatetime) now

**Comment by jm4games** [comment]
Well assuming time package calendar module is correct. This probably also works.
`
dayOfWeek :: C.Day -> C.DayOfWeek
dayOfWeek (C.Day d) = case mod (d + 3) 7 of
  0 -> C.sunday
  1 -> C.monday
  2 -> C.tuesday
  3 -> C.wednesday
  4 -> C.thursday
  5 -> C.friday
  _ -> C.saturday

`

**Comment by ssbothwell** [comment]
@chessai I can add those functions next weekend if you like.

**Comment by chessai** [comment]
@ssbothwell sounds dope! Would be much appreciated!

**Comment by jm4games** [comment]
Thanks for this fix on this guys, closing issue!
