### ISSUE TITLE
add more NFData instances

### ISSUE THREAD

**Issue by chessai** [andrewthad/chronos#52]

**Comment by ssbothwell** [comment]
I see there are a bunch in `bench.hs`. Which types still need instances for this?

**Comment by chessai** [comment]
Pretty much every type that can. Most, if not all, of them can be derived.
And the ones in bench should be moved over

**Comment by ssbothwell** [comment]
Cool, I can try to take this ticket.

**Comment by chessai** [comment]
@ssbothwell awesome! that would be much appreciated.
