### ISSUE TITLE
Build fails on 32 bit POSIX systems

### ISSUE THREAD

**Issue by kmicklas** [andrewthad/chronos#53]
This looks like the same issue as https://github.com/andrewthad/chronos/issues/35, but https://github.com/andrewthad/chronos/pull/36 only fixes it for Windows.

```
src/Chronos/Internal/CTimespec.hs:60:3: error:
    • Couldn't match type ‘Int32’ with ‘Int64’
      Expected type: IO Int64
        Actual type: IO Int32
    • In a stmt of a 'do' block: return ((s * 1000000000) + ns)
      In the expression:
        do CTimespec (CTime s) (CLong ns) <- alloca $ \ ptspec -> do ...
           return ((s * 1000000000) + ns)
      In an equation for ‘getPosixNanoseconds’:
          getPosixNanoseconds
            = do CTimespec (CTime s) (CLong ns) <- alloca $ \ ptspec -> ...
                 return ((s * 1000000000) + ns)
   |
60 |   return ((s * 1000000000) + ns)
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Specifically I am seeing this on `armv7a-unknown-linux-androideabi`.

**Comment by andrewthad** [comment]
I have a [PR for this](https://github.com/andrewthad/chronos/pull/54), but I don't have a 32-bit system available to try this on. If you can confirm that it works, I'll merge it.

**Comment by kmicklas** [comment]
@andrewthad It works for me on Android, thanks!

**Comment by andrewthad** [comment]
This has been released to hackage as part of `chronos-1.1.1`.

**Comment by chessai** [comment]
@andrewthad though the issue has been fixed already, remember i gave you that nix shell script for mocking 32-bit systems.

**Comment by andrewthad** [comment]
I’m not totally sure, because it definitely had built on a 32-bit posix system at some point. It’s possible that this part of the code changed since then in a subsequent refactor. Or it’s possible that CTime or CLong is defined differently on 32-bit ARM Android Linux than it is on 32-bit x86 Linux.
