### ISSUE TITLE
month is off by one on windows version

### ISSUE THREAD

**Issue by gbwey** [andrewthad/chronos#57]
Hi,
Just to let you know, in case you have Windows users.

>encode_YmdHMS SubsecondPrecisionAuto w3c . timeToDatetime <$> now
"2020-06-08T13:19:06.529"

>getCurrentTime
2020-05-08 13:19:14.125906 UTC

**Comment by andrewthad** [comment]
If anybody who uses Windows wants to PR a fix for this, please do. I have no way to confirm that it works, but it’s certainly worth fixing.

**Comment by gbwey** [comment]
Thanks
