### ISSUE TITLE
Builders don't zero-pad years

### ISSUE THREAD

**Issue by tek** [andrewthad/chronos#59]
encoding a date with `Year 1` results in `1-01-01`, which cannot be read by the parsers, since they use `parseFixedDigits 4`.
Is the date string `0001-01-01` invalid according to some standard or is this an oversight?

**Comment by andrewthad** [comment]
This is an oversight. I’m not actually sure what calendar-related RFCs say about encoding years prior to the year 1000. Intuitively, 0001-01-01 looks right to me. I’d take a PR changing the encoding behavior if someone can dig up what the RFC has to say.

**Comment by tek** [comment]
This states pretty clearly that years should be zero padded: https://tools.ietf.org/html/rfc3339

I'm a bit overwhelmed by the ceremony about padding in the code though – it looks like the equivalent here would be to create a vector of 10000 elements for a `Builder` to index??

**Comment by andrewthad** [comment]
You're right. A lookup table is a terrible option here. Look at [nanosecondsBuilderUtf8](https://hackage.haskell.org/package/chronos-1.1.1/docs/src/Chronos.html#nanosecondsBuilderUtf8) for inspiration:

```
nanosecondsBuilderUtf8 :: Int64 -> BB.Builder
nanosecondsBuilderUtf8 w
  | w == 0 = mempty
  | w > 99999999 = "." <> int64Builder w
  | w > 9999999 = ".0" <> int64Builder w
  | w > 999999 = ".00" <> int64Builder w
  | w > 99999 = ".000" <> int64Builder w
  | w > 9999 = ".0000" <> int64Builder w
  | w > 999 = ".00000" <> int64Builder w
  | w > 99 = ".000000" <> int64Builder w
  | w > 9 = ".0000000" <> int64Builder w
  | otherwise = ".00000000" <> int64Builder w
```

Something similar to that should be fine.

**Comment by tek** [comment]
created PR!
