### ISSUE TITLE
`normalYearMonthLength` in `Chronos.hs` uses 30 days for February instead of 28

### ISSUE THREAD

**Issue by zeme-wana** [andrewthad/chronos#67]
https://github.com/andrewthad/chronos/blob/922762f801ba07d72f82b48a8f14dc0842ab31bd/src/Chronos.hs#L842
The second number should be 28 for February, not 30.

**Comment by andrewthad** [comment]
Oh gosh! That’s not good. I wonder what’s broken by this. I’ll fix this the next time I’m at a computer if no one has made a PR by then.

**Comment by andrewthad** [comment]
Resolved by https://github.com/andrewthad/chronos/pull/72
