### ISSUE TITLE
Please publish the most recent dep. version bumps to hackage

### ISSUE THREAD

**Issue by jhrcek** [andrewthad/chronos#78]
Hello @andrewthad 
could you please release new version of chronos to hackage?
It would be great to have a version on hackage which supports all the latest versions of text, semigroups and aeson (which is what you have on master but is not yet available on hackage). This is the only thing that I'm missing from being able to switch my project to ghc 9.2.4 (without depending on specific package revision on github)

**Comment by teto** [comment]
same request but for ghc9.4 . It compiles fine, just need to bump (or even better REMOVE) the upper constraints

**Comment by teto** [comment]
lovely thank you !

**Comment by jhrcek** [comment]
Thank you, I really appreciate it :1st_place_medal:
